server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    dns: "root:root@tcp(127.0.0.1:3307)/realworld?parseTime=true&loc=Local"
jwt:
  secret: "hello"
